### ISSUE TITLE
Alsó felső margó

### ISSUE THREAD

**Issue by Gilgames32** [SCH-KB-PR/kbpr-ps#3]
Az alsó border vonalat levágja vagy csak nincs is ott. Valve please fix.

**Comment by Gilgames32** [comment]
https://github.com/Gilgames32/kbpr-ps/commit/b124d887c02d4b9450cbce2d56c03726d472bd5c commit javítja.
Nem tudom 2mm elég-e. @Bende126 ezt majd tesztelni kéne.

**Comment by Bende126** [comment]
Okkés, jövőhéten valami random quick time event keretein belül kipróbálom a 2mm-es margót

**Comment by Gilgames32** [comment]
szerintem jól működik, meg az új plotternél valszeg mindegy is, closing the issue
