### ISSUE TITLE
Magic number méretek

### ISSUE THREAD

**Issue by Gilgames32** [SCH-KB-PR/kbpr-ps#5]
Előző szkriptekbe bele volt hardcodeolva.
Margóra (UI) így már nem lenne szükség ha roll alapján fix, preset tratalmazza majd, ha nagyon módosítani kéne.
Margó UI helyén lehet valami más, majd kitalálom.

**Comment by Gilgames32** [comment]
Nem kéne elfelejteni hogy a nagyplakát borderless 🤭

**Comment by Gilgames32** [comment]
új plotternél jó kérdés mi a pálya, manualban lehet benne van vagy valamelyik programnál
@Bende126

**Comment by Bende126** [comment]
Am baszki kajak

1200 oldalas a manual, elkezdem olvasgatni és szólok ha találtam valamit

**Comment by Bende126** [comment]
Nah, meg vannak ez a [link](https://www.canon.com.cy/business/products/large-format-printers/imageprograf-pro-4600/specifications/) alapján.

Minimum nyomtatási méret:
- tekercs papír szélessége x 101.6mm
- vágott papír szélessége x 203.2mm

Maximum nyomtatási méret:
- tekercs papír szélessége x 18m
- vágott papír szélessége x 1.6m

Ajánlott margó:
- tekercs papír:
    - teteje: 20mm
    - allja: 3mm
    - oldalak: 3mm
- vágott papír:
    - teteje: 20mm
    - allja: 20mm
    - oldalak: 3mm

Minimum margó:
- tekercs papír:
    - teteje: 3mm
    - allja: 3mm
    - oldalak: 3mm
- vágott papír:
    - teteje: 3mm
    - allja: 20mm
    - oldalak: 3mm

**Comment by Bende126** [comment]
@Gilgames32

**Comment by Gilgames32** [comment]
köszii

**Comment by Gilgames32** [comment]
https://github.com/SCH-KB-PR/kbpr-ps/pull/16
