### ISSUE TITLE
Quick export png

### ISSUE THREAD

**Issue by Bende126** [SCH-KB-PR/kbpr-ps#8]
**A probléma, mely felvetette az ötletet**
Új a plotter és a plotter print pluginja licensz mögé van zárva.

**A megoldásod, ötleteid**
Quick export png checkbox: alapértelmezetten nincsen kipipálva, ha bepipálod rögtön exportálja az elkészített rácsot png-be, a betöltött kép mellé / külön mappába.

Esetleg be is zárja az elkészített rácsot.

**Miért lenne jó?**
Plussz idő spórolás

**Comment by Gilgames32** [comment]
added in https://github.com/SCH-KB-PR/kbpr-ps/commit/311bdc53831997631c8e37ef25faf0862d59ddc6
